### ISSUE TITLE
How to compile this on Linux?

### ISSUE THREAD

**Issue by eGax** [maikmerten/QuakeTextureTool#2]
You haven't made a new release in 8 years, but code changes in less than 1. How would one compile from the latest GitHub code here? 

I tried using `mvn package` in the `pom.xml` directory but it builds 2 jars : `QuakeTextureTool-1.0-SNAPSHOT-jar-with-dependencies.jar` & `QuakeTextureTool-1.0-SNAPSHOT.jar` and neither work with error `zsh: exec format error: ./QuakeTextureTool-1.0-SNAPSHOT.jar`

**Comment by maikmerten** [comment]
Hi eGax,

it appears you successfully compiled the Java source code - otherwise you wouldn't have the `.jar` archives in the `target` directory. So that looks fine!

Running `.jar` files is a bit different from normal Linux/Unix binaries: One needs to invoke `java` with the `-jar` option.

Please try `java -jar /path/to/QuakeTextureTool-1.0-SNAPSHOT-jar-with-dependencies.jar`(feel free to rename that `.jar`-file to something more to your liking and put it somewhere neat).

**Comment by eGax** [comment]
Funny. I just figured this out and was coming here to close this.

I TOTALLY forgot this and on my older distro install, I had a jar script to do this and forgot. I appreciate the response, TY.

For anyone else running Arch or Manjaro Linux if you have installed `maven` & `jdk-openjdk` you can compile this code from a terminal in the `/src` dir containing `pom.xml` with the command `mvn package`.

It will create a `target` dir with 2 jar packages. The package you will want will be `QuakeTextureTool-#.#-SNAPSHOT-jar-with-dependencies.jar` which you can rename to make it shorter or more friendly to remember. You can run it from the terminal with `java -jar yourjarnane.jar` or make an executable script some were in your path something like I have below. The jar can be anywhere, just make sure you link to it in your script.
```
#!/bin/bash
#
# quaketexturetool
# java dependency required to run
# 
exec java -jar ~/.local/bin/gametools/quaketexturetool/quaketexturetool-1.0.jar "$@"
@exit
```
